# Generated by Django 5.0.4 on 2024-05-01 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_delete_detail_post'),
        ('users', '0007_remove_post_user_id_remove_report_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_post',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(max_length=500)),
                ('date_comment', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
