# Generated by Django 5.0.3 on 2024-04-15 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_user', models.CharField(max_length=256)),
                ('age', models.FloatField(blank=True, null=True)),
                ('domain_work', models.CharField(blank=True, max_length=20, null=True)),
                ('numberphone', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('url_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result_text',
            fields=[
                ('id_text', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.CharField(max_length=10000)),
                ('date_save', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Result_file',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50)),
                ('date_save', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_pos', models.IntegerField()),
                ('number_neu', models.IntegerField()),
                ('number_neg', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('url_report', models.URLField()),
                ('number_pos', models.IntegerField()),
                ('number_neu', models.IntegerField()),
                ('number_neg', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('date_post', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_post', models.CharField(max_length=10000)),
                ('image_content_url', models.URLField(blank=True, null=True)),
                ('list_likes', models.TextField(blank=True, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_post',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(max_length=500)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
