# Generated by Django 5.0.4 on 2024-04-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post_title_post_alter_post_content_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail_post',
            old_name='id_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='detail_post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='result_file',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='result_text',
            old_name='user_id',
            new_name='user',
        ),
    ]
