# Generated by Django 5.0.4 on 2024-05-09 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_remove_post_user_id_remove_report_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result_file',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50)),
                ('date_save', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_pos', models.IntegerField()),
                ('number_neu', models.IntegerField()),
                ('number_neg', models.IntegerField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Result_text',
            fields=[
                ('id_text', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.CharField(max_length=10000)),
                ('date_save', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentiment', models.TextField(blank=True, null=True)),
                ('detail_sentiment', models.CharField(max_length=10000)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
